/* Autogenerated by png2wx.pl on Sat Mar 21 01:46:18 2015 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_circle;

#endif /* ICONS_H */
